# script créé le : Thu Dec 23 15:25:20 CET 2010 ;

# use  VOTRE_BASE_DE_DONNEE ;

DROP TABLE IF EXISTS E1 ;

CREATE TABLE E1 (id_E1 BIGINT NOT NULL,
PRIMARY KEY (id_E1) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS E2 ;

CREATE TABLE E2 (id_E2 BIGINT NOT NULL,
id_E1 BIGINT NOT NULL,
id_E1_a2 BIGINT NOT NULL,
id_E1_a3 BIGINT NOT NULL,
PRIMARY KEY (id_E2) ) ENGINE=InnoDB;

ALTER TABLE E2 ADD CONSTRAINT FK_E2_id_E1 FOREIGN KEY (id_E1) REFERENCES E1 (id_E1);

ALTER TABLE E2 ADD CONSTRAINT FK_E2_id_E1_a2 FOREIGN KEY (id_E1_a2) REFERENCES E1 (id_E1);

ALTER TABLE E2 ADD CONSTRAINT FK_E2_id_E1_a3 FOREIGN KEY (id_E1_a3) REFERENCES E1 (id_E1);

